### ISSUE TITLE
Empty search path given via `-L`

### ISSUE THREAD

**Issue by beatgammit** [kballard/rust-lua#25]
I fixed this on my machine:

    diff --git a/Makefile b/Makefile
    index b8d354c..9e61983 100644
    --- a/Makefile
    +++ b/Makefile
    @@ -2,7 +2,7 @@
     
     LUA_PCNAME = $(if $(shell pkg-config --exists lua5.1 && echo yes),lua5.1,lua)
     LUA_LIBNAME = $(firstword $(patsubst -llua%,lua%,$(filter -llua%,$(shell pkg-config --libs-only-l $(LUA_PCNAME)))))
    -LUA_LIBDIRS = $(patsubst -L%,%,$(shell pkg-config --libs-only-L $(LUA_PCNAME)))
    +LUA_LIBDIRS = $(patsubst %,%,$(shell pkg-config --libs-only-L $(LUA_PCNAME)))
     CFLAGS += $(shell pkg-config --cflags $(LUA_PCNAME))
     
     lib:
    @@ -26,7 +26,7 @@ else
     # the rest of the Makefile is only visible to Cargo
     
     cargo-prep: $(OUT_DIR)/config.rs
    -	@echo "cargo:rustc-flags=-l $(LUA_LIBNAME) -L native=$(LUA_LIBDIRS)"
    +	@echo "cargo:rustc-flags=-l $(LUA_LIBNAME) $(LUA_LIBDIRS)"
     
     $(OUT_DIR)/config.rs: $(OUT_DIR)/gen-config
        echo "pub mod config {" > $@

I don't know enough about `make` or linker arguments to know if this is the proper solution. For me, pkg-config --libs-only-L lua5.1 returns nothing, which is why this change works. I assume there was a reason for stripping the `-L` from `LUA_LIBDIRS` though, so I thought I'd submit this as an issue.

**Comment by kballard** [comment]
The `-L` from `pkg-config --libs-only-L` is not the same as the `-L` passed to `rustc`. Notably, when passing the flag to `rustc` I add an extra annotation so it only adds this to the search paths for native libraries.

**Comment by kballard** [comment]
Fixed in 9e20951748f8b5ddf1ba58beca84f8160f661cf2.
